version: '3'
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
  web:
    build: .
    ports:
    - 3000:3000
    environment:
      MONGODB_URI:  mongodb://root:example@mongo_db:27017/myFirstDatabase?authSource=admin
      PORT: 3000
      NODE_ENV: production
    depends_on:
    - mongo_db
volumes:
  mongo_db: {}
